### ISSUE TITLE
Complete and update existing Polish translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/Umweltzone#39]
It would be nice to have a Polish translation of the app. :poland: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/65762120-8babb580-e120-11e9-8277-29e21c5b9415.png)

# TODOs

- [x] Add new translations in `Umweltzone/src/main/res/values-pl/strings.xml` (ignore `config` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Do not translate `changelog.xml`.
  - Do append the German version of `zone_not_drawable_email_html_message` as done in `values/strings.xml`.
  - Do not add strings marked as `translatable="false"` to your files.
  - Do not modify, commit files outside of the `-pl` folder.
  - Escape special characters such as apostrophe `'` with their corresponding entity, e.g. `&#8217;`.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.
  - Put your name in the `Copyright` block at the top of the file.
- [x] Add new translations in `Umweltzone/src/main/res/values-pl/ckchangelog.xml`.
- [x] Review, complete and update existing translations in `values-pl/strings.xml` and `values-pl/ckchangelog.xml`.
- [x] Optional: Add new translations for FAQs in `Umweltzone/src/main/res/raw-pl/faqs.json`
  - The English and German files can be found in the `Umweltzone/src/main/res/raw/` and `Umweltzone/src/main/res/raw-de/` folders.
  ![faqs](https://user-images.githubusercontent.com/144518/65762365-25736280-e121-11e9-9070-bf9ca34a182c.png)
- [x] Update "Support languages" section in the README.md.

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by hexmind** [comment]
I can do it

**Comment by johnjohndoe** [comment]
@hexmind Nice. You are very welcome.

**Comment by johnjohndoe** [comment]
Please mind that I will **not** be able to reply quickly since I am on vacation for a while (Oct 3-31).

**Comment by hexmind** [comment]
Despite this fact please try find time for https://github.com/Umweltzone/Umweltzone/pull/44

**Comment by johnjohndoe** [comment]
@hexmind Please note that I updated the issue description.

**Comment by johnjohndoe** [comment]
Left to translate: FAQs and probably some new strings.

**Comment by rotsq** [comment]
I like to work on this
