### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/Umweltzone#48]
It would be nice to have a French translation of the app. :fr: 

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/65762120-8babb580-e120-11e9-8277-29e21c5b9415.png)

# TODOs

- [ ] Add new translations in `Umweltzone/src/main/res/values-fr/strings.xml` (ignore `config` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Do not translate `changelog.xml`.
  - Do append the German version of `zone_not_drawable_email_html_message` as done in `values/strings.xml`.
  - Do not add strings marked as `translatable="false"` to your files.
  - Escape special characters such as apostrophe `'` with their corresponding entity, e.g. `&#8217;`.
- [ ] Add new translations in `Umweltzone/src/main/res/values-fr/ckchangelog.xml`.
- [ ] Optional: Add new translations for FAQs in `Umweltzone/src/main/res/raw-fr/faqs.json`
  - The English and German files can be found in the `Umweltzone/src/main/res/raw/` and `Umweltzone/src/main/res/raw-de/` folders.
  ![faqs](https://user-images.githubusercontent.com/144518/65762365-25736280-e121-11e9-9070-bf9ca34a182c.png)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)
- [Testing contributions](https://github.com/Umweltzone/Umweltzone/tree/rip-uservoice#testing)

**Comment by laurerunser** [comment]
Hi ! I'd like to work on this !

**Comment by johnjohndoe** [comment]
@laurerunser Sure. Welcome to the project. Please let me know if you have any questions.
