### ISSUE TITLE
Add Portuguese translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/Umweltzone#81]
It would be nice to have a Portuguese translation of the app. :portugal: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/65762120-8babb580-e120-11e9-8277-29e21c5b9415.png)

# TODOs

- [x] Add new translations in `Umweltzone/src/main/res/values-pt/strings.xml` (ignore `config` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Do not translate `changelog.xml`.
  - Do append the German version of `zone_not_drawable_email_html_message` as done in `values/strings.xml`.
  - Do not add strings marked as `translatable="false"` to your files.
  - Do not modify, commit files outside of the `-pt` folder.
  - Escape special characters such as apostrophe `'` with their corresponding entity, e.g. `&#8217;`.
- [x] Add new translations in `Umweltzone/src/main/res/values-pt/ckchangelog.xml`.
- [x] Optional: Add new translations for FAQs in `Umweltzone/src/main/res/raw-pt/faqs.json`
  - The English and German files can be found in the `Umweltzone/src/main/res/raw/` and `Umweltzone/src/main/res/raw-de/` folders.
  ![faqs](https://user-images.githubusercontent.com/144518/65762365-25736280-e121-11e9-9070-bf9ca34a182c.png)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by romeroclaudino** [comment]
Good one @johnjohndoe! Thank you for creating the issue. I'm gonna take care of it!

**Comment by romeroclaudino** [comment]
Here you go, @johnjohndoe : #83 :-)
I've translated both the **strings.xml** and the **ckchangelog.xml** files.
Let me know if you have any doubt about it.

I would also like to translate the **faqs.json** file, but in this next week by creating another PR. Can we do that?

**Comment by johnjohndoe** [comment]
Hey @romeroclaudino. That was fast. Thank you. I will review it soon. Regarding the FAQ, you can submit it in a separate pull request. I am fine with that.

**Comment by larissayasin** [comment]
@johnjohndoe I can review the PR if you need it :)

**Comment by johnjohndoe** [comment]
@larissayasin You are welcome. Very kind of you.

**Comment by johnjohndoe** [comment]
@larissayasin, @romeroclaudino In case you have time there is a few more strings to translate: https://github.com/Umweltzone/roadsigns/issues
