### ISSUE TITLE
Add spanish translation

### ISSUE THREAD

**Issue by kevinesaa** [Umweltzone/Umweltzone#82]
For hacktoberfest, Can I translate it to spanish?

**Comment by johnjohndoe** [comment]
@kevinesaa, thank you for the kind offer. :heart_eyes_cat: Yes, you are welcome to translate the app to Spanish :es: 
Here is a "checklist" for you to follow along:

---

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/65762120-8babb580-e120-11e9-8277-29e21c5b9415.png)


# TODOs

- [ ] Add new translations in `Umweltzone/src/main/res/values-es/strings.xml` (ignore `config` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Do not translate `changelog.xml`.
  - Do append the German version of `zone_not_drawable_email_html_message` as done in `values/strings.xml`.
  - Do not add strings marked as `translatable="false"` to your files.
  - Do not modify, commit files outside of the `-es` folder.
  - Escape special characters such as apostrophe `'` with their corresponding entity, e.g. `&#8217;`.
- [ ] Add new translations in `Umweltzone/src/main/res/values-es/ckchangelog.xml`.
- [ ] Optional: Add new translations for FAQs in `Umweltzone/src/main/res/raw-es/faqs.json`
  - The English and German files can be found in the `Umweltzone/src/main/res/raw/` and `Umweltzone/src/main/res/raw-de/` folders.
  ![faqs](https://user-images.githubusercontent.com/144518/65762365-25736280-e121-11e9-9070-bf9ca34a182c.png)


# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

**Comment by kevinesaa** [comment]
@johnjohndoe, I have a question. Low emission zones, is about carbon emissions?

**Comment by johnjohndoe** [comment]
@kevinesaa Not exactly. It is about emissions of motorcycle engines. See [this Wikipedia article](https://en.wikipedia.org/wiki/Low-emission_zone).

**Comment by kevinesaa** [comment]
at the "SnackEngage" section, what "Power user" mean?

**Comment by kevinesaa** [comment]
> 
> 
> at the "SnackEngage" section, what "Power user" mean?

I translated like "admin user"

**Comment by kevinesaa** [comment]
I already make a pull request for the values-es. I will work the FAQs in other pull request

**Comment by johnjohndoe** [comment]
> > at the "SnackEngage" section, what "Power user" mean?
> 
> I translated like "admin user"

It refers to users which use the app **very often** and might be interested to become a tester.

**Comment by kevinesaa** [comment]
> > > at the "SnackEngage" section, what "Power user" mean?
> > 
> > I translated like "admin user"
> 
> It refers to users which use the app **very often** and might be interested to become a tester. "admin user" is not exactly what I meant with that.

Send me a screen capture to see all the context, and closer sentences.

**Comment by johnjohndoe** [comment]
The `snack_engage_beta_testing_title` snack popup is only shown to users who interact with the app for a longer time. The aim is to ask these _Power users_ to register as beta testers assuming they are willing to test new features as early as possible. Here is a screenshot with the snack popup at the bottom of the screen.

![Umweltzone app with Power user? snack](https://user-images.githubusercontent.com/144518/96040298-562c5400-0e6a-11eb-9ef6-870e820cb058.png)

**Comment by kevinesaa** [comment]
> 
> 
> The `snack_engage_beta_testing_title` snack popup is only shown to users who interact with the app for a longer time. The aim is to ask these _Power users_ to register as beta testers assuming they are willing to test new features as early as possible. Here is a screenshot with the snack popup at the bottom of the screen.
> 
> ![Umweltzone app with Power user? snack](https://user-images.githubusercontent.com/144518/96040298-562c5400-0e6a-11eb-9ef6-870e820cb058.png)

Maybe... something like "Do you want super power?". in spanish "¿Quieres super poderes?

**Comment by johnjohndoe** [comment]
Maybe "¿Tienes super poderes?"?

**Comment by kevinesaa** [comment]
> Maybe "¿Tienes super poderes?"?

That is like : "do you have super power?"

With "quieres", you are offering super powers; and with "tienes", you are asking if they already have the super power

**Comment by johnjohndoe** [comment]
"Tienes" sounds good to me. The English version basically asks: "Are you a power user?"

**Comment by johnjohndoe** [comment]
@kevinesaa Thank you for your contribution! If you don't have time to work on the translation of the FAQs please unassign yourself from this issue.
